export const LANG_DROPDOWN = [
  {
    id: 1,
    value: 'en',
    flag: '🇺🇸',
    label: 'English',
    sound: '/sound/EnglishOk.mp3',
  },
  {
    id: 2,
    value: 'vi',
    flag: '🇻🇳',
    label: 'Vietnamese',
    sound: '/sound/VietnameseOk.mp3',
  },
];

export const LANGUAGES = [
  {
    id: 1,
    img: '/images/iotem.png',
    gif: '/gif/Studio_Project1.gif',
    name: 'Online learning websites through video courses',
    languages: [
      'Html',
      'Css',
      'Php',
      'Javascript',
      'Jquery Ajax',
      'Databases:MySql',
    ],
    functions: [
      'Login',
      'Register',
      'Search',
      'Comment',
      'Password change',
      'user information',
      'Admin',
      '...',
    ],
    misson:
      'Full - stack, build the necessary functions. Responsive applications and Grid System design interfaces suitable for all devices.',
    link: 'http://ioteam.ml',
  },
  {
    id: 2,
    img: '/images/shoppi.png',
    gif: '/gif/Studio_Project2.gif',
    name: 'Website selling laptops',
    languages: ['Html', 'Css', 'Php', 'Javascript', 'Databases:MySql'],
    functions: [
      'Login',
      'Register',
      'Search',
      'Cart',
      'cart update',
      'Pay',
      'Admin',
      '...',
    ],
    misson:
      'Refer to available templates, design interfaces, learn MVC model structures, and program some product management functions.',
    link: 'http://laptoppi.ml',
  },
  {
    id: 3,
    img: '/images/landingpages.png',
    gif: '/gif/Studio_Project4.gif',
    name: 'Real estate landing page',
    languages: ['React', 'Html', 'Css', 'JavaScript'],
    functions: ['Wishlist', 'Details', 'Contacts'],
    misson:
      'Landing Page is to provide users with necessary information about the product. From the Landing Page collect information, call for their interaction with the item listed on the page.',
    link: 'https://landingpage-key.netlify.app',
  },
  {
    id: 4,
    img: '/images/shopnike.png',
    gif: '/gif/Studio_Project3.gif',
    name: 'PiShop-page',
    languages: ['NextJs', 'Typescript', 'Html', 'Css'],
    functions: ['cart', '...'],
    misson:
      'The site sells clothing and utensils and electrical appliances. This project is still under construction and will be launched soon.',
    link: 'https://ecommerce-key.netlify.app',
  },
  {
    id: 5,
    img: '/images/booking.png',
    gif: '/images/booking.png',
    name: 'Booking-page',
    languages: [
      'ReacrJs',
      'Javascript',
      'Html',
      'Css',
      'Databases:Express+mongodb',
    ],
    functions: [
      'login',
      'register',
      'JWT',
      'Book a room',
      'Search (type + date)',
      '...',
    ],
    misson:
      'The website serves to book online travel, work, ... The project is nearing completion and will be launched in the near future.',
    link: '#',
  },
  {
    id: 6,
    img: '/images/portfolio.png',
    gif: '/images/portfolio.png',
    name: 'Profile-page',
    languages: ['NextJs', 'Tailwind + Css', 'JavaScript(TypeScript)'],
    functions: [
      'Home',
      'About',
      'Services',
      'Portfolio',
      'Contacts',
      'Settings',
      'i18n',
      '...',
    ],
    misson:
      'The website was built to give employers a better understanding of me and my products.',
    link: '#',
  },
];

export const LANGUAGESVN = [
  {
    id: 1,
    img: '/images/iotem.png',
    gif: '',
    name: 'Trang web học trực tuyến thông qua các khóa học video',
    languages: ['Html', 'Css', 'Php', 'Javascript', 'Jquery Ajax'],
    functions: [
      'Đăng nhập',
      'Đăng ký',
      'Tìm kiếm',
      'Bình luận',
      'Thay đổi mật khẩu',
      'Thông tin người dùng',
      'Quản trị viên',
      '...',
    ],
    misson:
      'Full - stack, build các chức năng cần thiết. Ứng dụng Responsive và giao diện thiết kế Grid System phù hợp với mọi thiết bị.',
    link: 'http://ioteam.ml',
  },
  {
    id: 2,
    img: '/images/shoppi.png',
    gif: '',
    name: 'Website bán laptop',
    languages: ['Html', 'Css', 'Php', 'Javascript'],
    functions: [
      'Đăng nhập',
      'Đăng ký',
      'Tìm kiếm',
      'Xe đẩy',
      'cập nhật giỏ hàng',
      'Thanh toán',
      'Quản trị viên',
      '...',
    ],
    misson:
      'Tham khảo các mẫu có sẵn, thiết kế giao diện, tìm hiểu cấu trúc mô hình MVC, lập trình một số chức năng quản lý sản phẩm.',
    link: 'http://laptoppi.ml',
  },
  {
    id: 3,
    img: '/images/landingpages.png',
    gif: '',
    name: 'Trang web giới thiệu bất động sản',
    languages: ['React', 'Html', 'Css', 'JavaScript'],
    functions: ['Danh sách yêu thích', 'Chi tiết', 'Liên hệ'],
    misson:
      'Landing Page là cung cấp cho người dùng những thông tin cần thiết về sản phẩm. Từ Landing Page thu thập thông tin, kêu gọi tương tác của họ với mục được liệt kê trên trang.',
    link: 'https://landingpage-key.netlify.app',
  },
  {
    id: 4,
    img: '/images/shopnike.png',
    gif: '/gif/Studio_Project3.gif',
    name: 'PiShop-page',
    languages: ['NextJs', 'Typescript', 'Html', 'Css'],
    functions: ['Giỏ hàng', '...'],
    misson:
      'Trang web bán quần áo và đồ dùng và các thiết bị điện . Dự án này còn đang trong quá trình xây dựng và sẽ sớm ra mắt',
    link: 'https://ecommerce-key.netlify.app',
  },
  {
    id: 5,
    img: '/images/booking.png',
    gif: '/images/booking.png',
    name: 'Booking-page',
    languages: ['ReacrJs', 'Javascript', 'Html', 'Css'],
    functions: [
      'Đăng nhập',
      'Đăng ký',
      'JWT',
      'Đặt phòng',
      'Tìm kiếm (loại ngày)',
      'Quản trị viên',
      '...',
    ],
    misson:
      'Trang web phục vụ đặt phòng online du lịch, làm việc , ... Dự án sắp hoàn thành và sẽ cho ra mắt trong thời gian tới.',
    link: '#',
  },
  {
    id: 6,
    img: '/images/portfolio.png',
    gif: '/images/portfolio.png',
    name: 'Profile-page',
    languages: ['NextJs', 'Tailwind + Css', 'JavaScript(TypeScript)'],
    functions: [
      'Trang chủ',
      'Giới thiệu',
      'Dịch vụ',
      'Dự án',
      'Danh bạ',
      'Cài đặt',
      // 'i18n',
      '...',
    ],
    misson:
      'Trang web được xây dựng nhằm mục đích để cho nhà tuyển dụng hiểu rõ hơn về tôi và những sản phẩm của tôi.',
    link: '#',
  },
];
